# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'logstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogstream.proto\x12\tlogstream\"=\n\x08LogEvent\x12\r\n\x05level\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"!\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\",\n\x0cQueryRequest\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"4\n\rQueryResponse\x12#\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x13.logstream.LogEvent\"\x10\n\x0eMetricsRequest\"o\n\x0fMetricsResponse\x12\x19\n\x11\x65vents_per_second\x18\x01 \x01(\x01\x12\x16\n\x0ep99_latency_us\x18\x02 \x01(\x01\x12\x14\n\x0ctotal_events\x18\x03 \x01(\x04\x12\x13\n\x0b\x62uffer_size\x18\x04 \x01(\x04\x32\xcd\x01\n\x10LogStreamService\x12\x38\n\x06Ingest\x12\x13.logstream.LogEvent\x1a\x19.logstream.IngestResponse\x12:\n\x05Query\x12\x17.logstream.QueryRequest\x1a\x18.logstream.QueryResponse\x12\x43\n\nGetMetrics\x12\x19.logstream.MetricsRequest\x1a\x1a.logstream.MetricsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGEVENT']._serialized_start=30
  _globals['_LOGEVENT']._serialized_end=91
  _globals['_INGESTRESPONSE']._serialized_start=93
  _globals['_INGESTRESPONSE']._serialized_end=126
  _globals['_QUERYREQUEST']._serialized_start=128
  _globals['_QUERYREQUEST']._serialized_end=172
  _globals['_QUERYRESPONSE']._serialized_start=174
  _globals['_QUERYRESPONSE']._serialized_end=226
  _globals['_METRICSREQUEST']._serialized_start=228
  _globals['_METRICSREQUEST']._serialized_end=244
  _globals['_METRICSRESPONSE']._serialized_start=246
  _globals['_METRICSRESPONSE']._serialized_end=357
  _globals['_LOGSTREAMSERVICE']._serialized_start=360
  _globals['_LOGSTREAMSERVICE']._serialized_end=565
# @@protoc_insertion_point(module_scope)
