# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logstream_pb2 as logstream__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logstream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogStreamServiceStub(object):
    """─────────────────────────────────────────────
    the service — defines what functions C++ exposes to Python
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ingest = channel.unary_unary(
                '/logstream.LogStreamService/Ingest',
                request_serializer=logstream__pb2.LogEvent.SerializeToString,
                response_deserializer=logstream__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.Query = channel.unary_unary(
                '/logstream.LogStreamService/Query',
                request_serializer=logstream__pb2.QueryRequest.SerializeToString,
                response_deserializer=logstream__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/logstream.LogStreamService/GetMetrics',
                request_serializer=logstream__pb2.MetricsRequest.SerializeToString,
                response_deserializer=logstream__pb2.MetricsResponse.FromString,
                _registered_method=True)


class LogStreamServiceServicer(object):
    """─────────────────────────────────────────────
    the service — defines what functions C++ exposes to Python
    ─────────────────────────────────────────────

    """

    def Ingest(self, request, context):
        """Python calls this to send a log event to C++
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Python calls this to search stored logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Python calls this to get current performance metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogStreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=logstream__pb2.LogEvent.FromString,
                    response_serializer=logstream__pb2.IngestResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=logstream__pb2.QueryRequest.FromString,
                    response_serializer=logstream__pb2.QueryResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=logstream__pb2.MetricsRequest.FromString,
                    response_serializer=logstream__pb2.MetricsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logstream.LogStreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logstream.LogStreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogStreamService(object):
    """─────────────────────────────────────────────
    the service — defines what functions C++ exposes to Python
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logstream.LogStreamService/Ingest',
            logstream__pb2.LogEvent.SerializeToString,
            logstream__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logstream.LogStreamService/Query',
            logstream__pb2.QueryRequest.SerializeToString,
            logstream__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logstream.LogStreamService/GetMetrics',
            logstream__pb2.MetricsRequest.SerializeToString,
            logstream__pb2.MetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
