// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: logstream.proto

#include "logstream.pb.h"
#include "logstream.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace logstream {

static const char* LogStreamService_method_names[] = {
  "/logstream.LogStreamService/Ingest",
  "/logstream.LogStreamService/Query",
  "/logstream.LogStreamService/GetMetrics",
};

std::unique_ptr< LogStreamService::Stub> LogStreamService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LogStreamService::Stub> stub(new LogStreamService::Stub(channel, options));
  return stub;
}

LogStreamService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Ingest_(LogStreamService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Query_(LogStreamService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetMetrics_(LogStreamService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LogStreamService::Stub::Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::logstream::IngestResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::logstream::LogEvent, ::logstream::IngestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ingest_, context, request, response);
}

void LogStreamService::Stub::async::Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::logstream::LogEvent, ::logstream::IngestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ingest_, context, request, response, std::move(f));
}

void LogStreamService::Stub::async::Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ingest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>* LogStreamService::Stub::PrepareAsyncIngestRaw(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::logstream::IngestResponse, ::logstream::LogEvent, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ingest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>* LogStreamService::Stub::AsyncIngestRaw(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIngestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LogStreamService::Stub::Query(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::logstream::QueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::logstream::QueryRequest, ::logstream::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Query_, context, request, response);
}

void LogStreamService::Stub::async::Query(::grpc::ClientContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::logstream::QueryRequest, ::logstream::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, response, std::move(f));
}

void LogStreamService::Stub::async::Query(::grpc::ClientContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>* LogStreamService::Stub::PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::logstream::QueryResponse, ::logstream::QueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Query_, context, request);
}

::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>* LogStreamService::Stub::AsyncQueryRaw(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LogStreamService::Stub::GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::logstream::MetricsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::logstream::MetricsRequest, ::logstream::MetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMetrics_, context, request, response);
}

void LogStreamService::Stub::async::GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::logstream::MetricsRequest, ::logstream::MetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetrics_, context, request, response, std::move(f));
}

void LogStreamService::Stub::async::GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMetrics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>* LogStreamService::Stub::PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::logstream::MetricsResponse, ::logstream::MetricsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMetrics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>* LogStreamService::Stub::AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMetricsRaw(context, request, cq);
  result->StartCall();
  return result;
}

LogStreamService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LogStreamService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LogStreamService::Service, ::logstream::LogEvent, ::logstream::IngestResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LogStreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::logstream::LogEvent* req,
             ::logstream::IngestResponse* resp) {
               return service->Ingest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LogStreamService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LogStreamService::Service, ::logstream::QueryRequest, ::logstream::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LogStreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::logstream::QueryRequest* req,
             ::logstream::QueryResponse* resp) {
               return service->Query(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LogStreamService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LogStreamService::Service, ::logstream::MetricsRequest, ::logstream::MetricsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LogStreamService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::logstream::MetricsRequest* req,
             ::logstream::MetricsResponse* resp) {
               return service->GetMetrics(ctx, req, resp);
             }, this)));
}

LogStreamService::Service::~Service() {
}

::grpc::Status LogStreamService::Service::Ingest(::grpc::ServerContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LogStreamService::Service::Query(::grpc::ServerContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LogStreamService::Service::GetMetrics(::grpc::ServerContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace logstream
#include <grpcpp/ports_undef.inc>

