// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: engine/proto/logstream.proto
// Original file comments:
// proto3 is the current version of the protobuf language
#ifndef GRPC_engine_2fproto_2flogstream_2eproto__INCLUDED
#define GRPC_engine_2fproto_2flogstream_2eproto__INCLUDED

#include "engine/proto/logstream.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace logstream {

// ─────────────────────────────────────────────
// the service — defines what functions C++ exposes to Python
// ─────────────────────────────────────────────
//
class LogStreamService final {
 public:
  static constexpr char const* service_full_name() {
    return "logstream.LogStreamService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Python calls this to send a log event to C++
    virtual ::grpc::Status Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::logstream::IngestResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::IngestResponse>> AsyncIngest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::IngestResponse>>(AsyncIngestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::IngestResponse>> PrepareAsyncIngest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::IngestResponse>>(PrepareAsyncIngestRaw(context, request, cq));
    }
    // Python calls this to search stored logs
    virtual ::grpc::Status Query(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::logstream::QueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::QueryResponse>> AsyncQuery(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::QueryResponse>>(AsyncQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::QueryResponse>> PrepareAsyncQuery(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::QueryResponse>>(PrepareAsyncQueryRaw(context, request, cq));
    }
    // Python calls this to get current performance metrics
    virtual ::grpc::Status GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::logstream::MetricsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::MetricsResponse>> AsyncGetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::MetricsResponse>>(AsyncGetMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::MetricsResponse>> PrepareAsyncGetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::logstream::MetricsResponse>>(PrepareAsyncGetMetricsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Python calls this to send a log event to C++
      virtual void Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Python calls this to search stored logs
      virtual void Query(::grpc::ClientContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Query(::grpc::ClientContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Python calls this to get current performance metrics
      virtual void GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logstream::IngestResponse>* AsyncIngestRaw(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logstream::IngestResponse>* PrepareAsyncIngestRaw(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logstream::QueryResponse>* AsyncQueryRaw(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logstream::QueryResponse>* PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logstream::MetricsResponse>* AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::logstream::MetricsResponse>* PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::logstream::IngestResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>> AsyncIngest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>>(AsyncIngestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>> PrepareAsyncIngest(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>>(PrepareAsyncIngestRaw(context, request, cq));
    }
    ::grpc::Status Query(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::logstream::QueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>> AsyncQuery(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>>(AsyncQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>> PrepareAsyncQuery(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>>(PrepareAsyncQueryRaw(context, request, cq));
    }
    ::grpc::Status GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::logstream::MetricsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>> AsyncGetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>>(AsyncGetMetricsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>> PrepareAsyncGetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>>(PrepareAsyncGetMetricsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response, std::function<void(::grpc::Status)>) override;
      void Ingest(::grpc::ClientContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Query(::grpc::ClientContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      void Query(::grpc::ClientContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetMetrics(::grpc::ClientContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>* AsyncIngestRaw(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logstream::IngestResponse>* PrepareAsyncIngestRaw(::grpc::ClientContext* context, const ::logstream::LogEvent& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>* AsyncQueryRaw(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logstream::QueryResponse>* PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::logstream::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>* AsyncGetMetricsRaw(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::logstream::MetricsResponse>* PrepareAsyncGetMetricsRaw(::grpc::ClientContext* context, const ::logstream::MetricsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Ingest_;
    const ::grpc::internal::RpcMethod rpcmethod_Query_;
    const ::grpc::internal::RpcMethod rpcmethod_GetMetrics_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Python calls this to send a log event to C++
    virtual ::grpc::Status Ingest(::grpc::ServerContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response);
    // Python calls this to search stored logs
    virtual ::grpc::Status Query(::grpc::ServerContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response);
    // Python calls this to get current performance metrics
    virtual ::grpc::Status GetMetrics(::grpc::ServerContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Ingest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Ingest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Ingest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ingest(::grpc::ServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIngest(::grpc::ServerContext* context, ::logstream::LogEvent* request, ::grpc::ServerAsyncResponseWriter< ::logstream::IngestResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Query() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuery(::grpc::ServerContext* context, ::logstream::QueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::logstream::QueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetMetrics() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetrics(::grpc::ServerContext* context, ::logstream::MetricsRequest* request, ::grpc::ServerAsyncResponseWriter< ::logstream::MetricsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Ingest<WithAsyncMethod_Query<WithAsyncMethod_GetMetrics<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Ingest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Ingest() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::logstream::LogEvent, ::logstream::IngestResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::logstream::LogEvent* request, ::logstream::IngestResponse* response) { return this->Ingest(context, request, response); }));}
    void SetMessageAllocatorFor_Ingest(
        ::grpc::MessageAllocator< ::logstream::LogEvent, ::logstream::IngestResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::logstream::LogEvent, ::logstream::IngestResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Ingest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ingest(::grpc::ServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ingest(
      ::grpc::CallbackServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Query() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::logstream::QueryRequest, ::logstream::QueryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::logstream::QueryRequest* request, ::logstream::QueryResponse* response) { return this->Query(context, request, response); }));}
    void SetMessageAllocatorFor_Query(
        ::grpc::MessageAllocator< ::logstream::QueryRequest, ::logstream::QueryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::logstream::QueryRequest, ::logstream::QueryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Query(
      ::grpc::CallbackServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetMetrics() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::logstream::MetricsRequest, ::logstream::MetricsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::logstream::MetricsRequest* request, ::logstream::MetricsResponse* response) { return this->GetMetrics(context, request, response); }));}
    void SetMessageAllocatorFor_GetMetrics(
        ::grpc::MessageAllocator< ::logstream::MetricsRequest, ::logstream::MetricsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::logstream::MetricsRequest, ::logstream::MetricsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Ingest<WithCallbackMethod_Query<WithCallbackMethod_GetMetrics<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Ingest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Ingest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Ingest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ingest(::grpc::ServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Query() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetMetrics() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Ingest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Ingest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Ingest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ingest(::grpc::ServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestIngest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Query() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetMetrics() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetMetrics(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Ingest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Ingest() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Ingest(context, request, response); }));
    }
    ~WithRawCallbackMethod_Ingest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Ingest(::grpc::ServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Ingest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Query() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Query(context, request, response); }));
    }
    ~WithRawCallbackMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Query(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetMetrics() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetMetrics(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetMetrics(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Ingest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Ingest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::logstream::LogEvent, ::logstream::IngestResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::logstream::LogEvent, ::logstream::IngestResponse>* streamer) {
                       return this->StreamedIngest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Ingest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Ingest(::grpc::ServerContext* /*context*/, const ::logstream::LogEvent* /*request*/, ::logstream::IngestResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedIngest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::logstream::LogEvent,::logstream::IngestResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Query : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Query() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::logstream::QueryRequest, ::logstream::QueryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::logstream::QueryRequest, ::logstream::QueryResponse>* streamer) {
                       return this->StreamedQuery(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Query() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Query(::grpc::ServerContext* /*context*/, const ::logstream::QueryRequest* /*request*/, ::logstream::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::logstream::QueryRequest,::logstream::QueryResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetMetrics : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetMetrics() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::logstream::MetricsRequest, ::logstream::MetricsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::logstream::MetricsRequest, ::logstream::MetricsResponse>* streamer) {
                       return this->StreamedGetMetrics(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetMetrics() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetMetrics(::grpc::ServerContext* /*context*/, const ::logstream::MetricsRequest* /*request*/, ::logstream::MetricsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetMetrics(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::logstream::MetricsRequest,::logstream::MetricsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Ingest<WithStreamedUnaryMethod_Query<WithStreamedUnaryMethod_GetMetrics<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Ingest<WithStreamedUnaryMethod_Query<WithStreamedUnaryMethod_GetMetrics<Service > > > StreamedService;
};

}  // namespace logstream


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_engine_2fproto_2flogstream_2eproto__INCLUDED
